---
permalink: online-help-96-97/concept_date_time.html 
sidebar: sidebar 
keywords: date, time, settings, cluster, system, manager, online, help 
summary: Puede usar System Manager para gestionar la configuración de fecha y hora de un clúster. 
---
= Gestione la configuración de fecha y hora de un clúster con System Manager: ONTAP 9.7 y versiones anteriores
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible usar System Manager Classic de ONTAP (disponible en ONTAP 9.7 y versiones anteriores) para gestionar la configuración de fecha y hora de un clúster.



== Fecha y hora

La ventana de fecha y hora le permite ver las configuraciones actuales de fecha y hora del sistema de almacenamiento y modificar las opciones cuando sea necesario.



=== Botones de comando

* *Edición*
+
Abre el cuadro de diálogo Editar fecha y hora, que permite editar los servidores de hora.

* *Actualizar*
+
Actualiza la información de la ventana.





=== El área Detalles

En el área de detalles, se muestra información acerca de la fecha, la hora, la zona horaria, el servicio NTP y los servidores de hora del sistema de almacenamiento.

*Información relacionada*

xref:task_setting_time_zone_for_cluster.adoc[Configurar la zona horaria de un clúster]

xref:task_setting_up_network_when_ip_address_range_is_disabled.adoc[Configuración de una red cuando se deshabilita un rango de direcciones IP]

https://docs.netapp.com/us-en/ontap/system-admin/index.html["Administración del sistema"]
