---
permalink: online-help-96-97/concept_export_policies.html 
sidebar: sidebar 
keywords: system, manager, create, edit, manage, export, policy, online, help, volume, rules, svm, qtree, rename 
summary: Se puede usar System Manager para crear, editar y gestionar políticas de exportación. 
---
= Gestione políticas de exportación con System Manager: ONTAP 9.7 y versiones anteriores
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede usar el clásico de System Manager de ONTAP (disponible en ONTAP 9.7 y versiones anteriores) para crear, editar y gestionar políticas de exportación.



== Cree una política de exportación

Puede usar System Manager para crear una política de exportación de modo que los clientes puedan acceder a volúmenes concretos.

.Pasos
. Haga clic en *almacenamiento* > *SVM*.
. Seleccione la SVM y, a continuación, haga clic en *Configuración de SVM*.
. En el panel *Directivas*, haga clic en *políticas de exportación*.
. Haga clic en *Crear*.
. En el cuadro de diálogo *Crear directiva de exportación*, especifique un nombre para la directiva de exportación.
. Si desea crear una política de exportación copiando las reglas de una ya existente, active la casilla de comprobación *Copy Rules from* y, a continuación, seleccione la máquina virtual de almacenamiento (SVM) y la política de exportación.
+
No se debe seleccionar la SVM de destino para la recuperación de desastres en el menú desplegable para crear una política de exportación.

. En el área **Export Rules**, haga clic en *Agregar* para agregar reglas a la política de exportación.
. Haga clic en *Crear*.
. Compruebe que la directiva de exportación que ha creado se muestra en la ventana *Directivas de exportación*.




== Cambiar el nombre de las políticas de exportación

Puede utilizar System Managerto para cambiar el nombre de una directiva de exportación existente.

.Pasos
. Haga clic en *almacenamiento* > *SVM*.
. Seleccione la SVM y, a continuación, haga clic en *Configuración de SVM*.
. En el panel *Directivas*, haga clic en *políticas de exportación*.
. Seleccione la directiva de exportación a la que desea cambiar el nombre y, a continuación, haga clic en *Cambiar nombre de directiva*.
. En el cuadro de diálogo *Cambiar nombre de directiva*, especifique un nuevo nombre de directiva y, a continuación, haga clic en *Modificar*.
. Compruebe los cambios realizados en la ventana *Directivas de exportación*.




== Elimine las políticas de exportación

Puede usar System Manager para eliminar políticas de exportación que ya no se necesitan.

.Pasos
. Haga clic en *almacenamiento* > *SVM*.
. Seleccione la SVM y, a continuación, haga clic en *Configuración de SVM*.
. En el panel *Directivas*, haga clic en *políticas de exportación*.
. Seleccione la directiva de exportación que desea eliminar y, a continuación, haga clic en *Eliminar directiva*.
. Active la casilla de verificación de confirmación y, a continuación, haga clic en *Eliminar*.




== Añada reglas a una política de exportación

Puede usar System Manager para añadir reglas a una política de exportación, lo que le permitirá definir el acceso de los clientes a los datos.

.Antes de empezar
Debe haber creado la política de exportación a la que se añadirán las reglas de exportación.

.Pasos
. Haga clic en *almacenamiento* > *SVM*.
. Seleccione la SVM y, a continuación, haga clic en *Configuración de SVM*.
. En el panel *Directivas*, haga clic en *políticas de exportación*.
. Seleccione la directiva de exportación a la que desea agregar reglas y, en la ficha *Reglas de exportación*, haga clic en *Agregar*.
. En el cuadro de diálogo *Crear regla de exportación*, realice los siguientes pasos:
+
.. Especifique el cliente que requiere acceso a los datos.
+
Puede especificar varios clientes como valores separados por comas.

+
Puede especificar el cliente con cualquiera de los siguientes formatos:

+
*** Como nombre de host; por ejemplo, host1
*** Como dirección IPv4; por ejemplo, 10.1.12.24
*** Como dirección IPv4 con una máscara de red; por ejemplo, 10.1.16.0/255.255.255.0
*** Como dirección IPv6; por ejemplo, FE80::0202:B3FF:FE1E:8329
*** Como dirección IPv6 con una máscara de red; por ejemplo, 2001:db8:/32
*** Como un netgroup, con el nombre del netgroup precedido por un símbolo de AT (@); por ejemplo, @netgroup
*** Como nombre de dominio precedido por un punto (.); por ejemplo, .example.com


+
[NOTE]
====
No introduzca un rango de direcciones IP, como 10.1.12.10 hasta 10.1.12.70. Las entradas con este formato se interpretan como cadenas de texto y se consideran nombres de host.

====
+
Puede introducir la dirección IPv4 `0.0.0.0/0` proporcionar acceso a todos los hosts.

.. Si desea modificar el número de índice de regla, seleccione el que corresponda.
.. Seleccione uno o varios protocolos de acceso.
+
Si no selecciona ningún protocolo de acceso, el valor predeterminado "'any'" se asignará a la regla de exportación.

.. Seleccione uno o varios tipos de seguridad y las reglas de acceso.


. Haga clic en *Aceptar*.
. Compruebe que la regla de exportación que ha agregado se muestra en la pestaña *Reglas de exportación* de la política de exportación seleccionada.




== Modifique las reglas de la política de exportación

Puede usar System Manager para modificar el cliente, los protocolos de acceso y los permisos de acceso especificados de una regla de política de exportación.

.Pasos
. Haga clic en *almacenamiento* > *SVM*.
. Seleccione la SVM y, a continuación, haga clic en *Configuración de SVM*.
. En el panel *Directivas*, haga clic en *políticas de exportación*.
. En la ventana *Directivas de exportación*, seleccione la directiva de exportación para la que desea editar la regla de exportación y, en la ficha *Reglas de exportación*, seleccione la regla que desea editar y, a continuación, haga clic en *Editar*.
. Modifique los siguientes parámetros según sea necesario:
+
** Especificación del cliente
** Protocolos de acceso
** Detalles de acceso


. Haga clic en *Aceptar*.
. Compruebe que los cambios actualizados de la regla de exportación se muestran en la pestaña *Reglas de exportación*.




== Elimine las reglas de política de exportación

Puede usar System Manager para eliminar reglas de políticas de exportación que ya no se necesitan.

.Pasos
. Haga clic en *almacenamiento* > *SVM*.
. Seleccione la SVM y, a continuación, haga clic en *Configuración de SVM*.
. En el panel *Directivas*, haga clic en *políticas de exportación*.
. Seleccione la política de exportación sobre la que desea eliminar la regla de exportación.
. En la ficha *Reglas de exportación*, seleccione la regla de exportación que desea eliminar y, a continuación, haga clic en *Eliminar*.
. En el cuadro de confirmación, haga clic en *Eliminar*.




== Cómo las políticas de exportación controlan el acceso de los clientes a volúmenes o qtrees

Las políticas de exportación contienen una o varias _reglas de exportación_ que procesan cada solicitud de acceso de cliente. El resultado del proceso determina si se deniega o se concede acceso al cliente y qué nivel de acceso. Para que los clientes accedan a los datos, debe haber una política de exportación con reglas de exportación en la máquina virtual de almacenamiento (SVM).

Se asocia exactamente una política de exportación a cada volumen o qtree para configurar el acceso de los clientes al volumen o qtree. La SVM puede contener varias políticas de exportación. Esto le permite hacer lo siguiente para las SVM con varios volúmenes o qtrees:

* Asigne diferentes políticas de exportación a cada volumen o qtree de la SVM para controlar el acceso de cliente individual a cada volumen o qtree de la SVM.
* Asigne la misma política de exportación a varios volúmenes o qtrees de la SVM para un control de acceso del cliente idéntico sin que tenga que crear una nueva política de exportación para cada volumen o qtree.


Si un cliente realiza una solicitud de acceso que no está permitida por la política de exportación aplicable, la solicitud falla con un mensaje de permiso denegado. Si un cliente no coincide con ninguna regla de la política de exportación, se deniega el acceso. Si una política de exportación está vacía, se deniegan implícitamente todos los accesos.

Puede modificar dinámicamente una política de exportación en un sistema que ejecuta ONTAP.



== Políticas de exportación

La ventana Export Policies se puede utilizar para crear, ver y gestionar información acerca de las políticas de exportación y sus reglas de exportación relacionadas.



=== Políticas de exportación

La ventana Export Policies permite ver y gestionar las políticas de exportación creadas para la máquina virtual de almacenamiento (SVM).

* *Botones de comando*
+
** Cree
+
Se abre el cuadro de diálogo Create Export Policy, que permite crear una política de exportación y agregar reglas de exportación. También se pueden copiar reglas de exportación desde una SVM existente.

** Cambiar el nombre
+
Abre el cuadro de diálogo Cambiar nombre de directiva, que permite cambiar el nombre de la política de exportación seleccionada.

** Eliminar
+
Abre el cuadro de diálogo Delete Export Policy, que permite eliminar la política de exportación seleccionada.

** Actualice
+
Actualiza la información de la ventana.







=== Pestaña Export Rules

La pestaña Export Rules permite ver información sobre las reglas de exportación creadas para una determinada política de exportación. También puede agregar, editar y eliminar reglas.

* *Botones de comando*
+
** Agregar
+
Abre el cuadro de diálogo Create Export Rule, que permite añadir una regla de exportación a la política de exportación seleccionada.

** Editar
+
Abre el cuadro de diálogo Modificar regla de exportación, que permite modificar los atributos de la regla de exportación seleccionada.

** Eliminar
+
Abre el cuadro de diálogo Eliminar regla de exportación, que permite eliminar la regla de exportación seleccionada.

** Arriba
+
Mueve hacia arriba el índice de reglas de la regla de exportación seleccionada.

** Abajo
+
Baja el índice de reglas de la regla de exportación seleccionada.

** Actualice
+
Actualiza la información de la ventana.



* *Lista de reglas de exportación*
+
** Índice de reglas
+
Especifica la prioridad en función de la cual se procesen las reglas de exportación. Puede utilizar los botones Subir y bajar para elegir la prioridad.

** Cliente
+
Especifica el cliente al que se aplica la regla.

** Protocolos de acceso
+
Muestra el protocolo de acceso especificado para la regla de exportación.

+
Si no ha especificado ningún protocolo de acceso, se considerará el valor predeterminado «'any'».

** Regla de sólo lectura
+
Especifica uno o varios tipos de seguridad para el acceso de sólo lectura.

** Regla de lectura/escritura
+
Especifica uno o varios tipos de seguridad para acceso de lectura/escritura.

** Acceso de superusuario
+
Especifica el tipo o tipos de seguridad para el acceso de superusuario.







=== Pestaña objetos asignados

La pestaña Assigned Objects permite ver los volúmenes y qtrees que están asignados a la política de exportación seleccionada. También se puede ver si el volumen está cifrado o no.

*Información relacionada*

xref:task_setting_up_cifs.adoc[Configuración de CIFS]
