---
permalink: online-help-96-97/concept_shares.html 
sidebar: sidebar 
keywords: online, help, share, system, manager, qtress, cifs, create, edit, manage, share, access, stop, home, directory, configure, smb 
summary: Puede usar System Manager para crear, editar y gestionar recursos compartidos. 
---
= Gestione recursos compartidos con System Manager: ONTAP 9.7 y versiones anteriores
:allow-uri-read: 


Es posible usar el clásico de System Manager de ONTAP (disponible en ONTAP 9.7 y versiones anteriores) para crear, editar y gestionar recursos compartidos.



== Cree un recurso compartido CIFS

Puede usar System Manager para crear un recurso compartido de CIFS que permite especificar la carpeta, el qtree o el volumen a los que pueden acceder los usuarios CIFS.

.Antes de empezar
Debe haber instalado la licencia CIFS antes de configurar e iniciar CIFS.

.Pasos
. Haga clic en *almacenamiento* > *recursos compartidos*.
. En el menú desplegable del campo *SVM*, seleccione la SVM en la que desea crear un recurso compartido CIFS.
. Haga clic en *Crear recurso compartido*.
. En la ventana *Crear recurso compartido*, haga clic en *examinar* y, a continuación, seleccione la carpeta, qtree o volumen que se debe compartir.
. Escriba un nombre para el nuevo recurso compartido CIFS.
. *Opcional:* Active la casilla de verificación *Activar disponibilidad continua para Hyper-V y SQL* para permitir que los clientes compatibles con SMB 3.0 y versiones posteriores abran archivos de forma persistente durante operaciones no disruptivas.
+
Los archivos que se abren con esta opción están protegidos de eventos disruptivos como conmutación al nodo de respaldo, devolución y migración LIF.

+
A partir de System Manager 9.6, es compatible con la disponibilidad continua de los volúmenes FlexGroup.

. Active la casilla de verificación *cifrar datos mientras accede a este recurso compartido* para habilitar el cifrado SMB 3.0.
. Proporcione una descripción o un comentario para el recurso compartido y, a continuación, haga clic en *Crear*.


.Resultados
El recurso compartido de CIFS se crea con los permisos de acceso establecidos en «'Control total para todos'» del grupo.



== Detenga el acceso a recursos compartidos

Puede usar System Manager para detener un recurso compartido cuando desea quitar el acceso de red compartido a una carpeta, un qtree o un volumen.

.Antes de empezar
Debe haber instalado la licencia de CIFS.

.Pasos
. Haga clic en *almacenamiento* > *recursos compartidos*.
. En el menú desplegable del campo *SVM*, seleccione la SVM en la que reside el recurso compartido CIFS que desea detener.
. En la lista de recursos compartidos, seleccione el recurso compartido que desea dejar de compartir y, a continuación, haga clic en *Detener uso compartido*.
. Active la casilla de verificación de confirmación y, a continuación, haga clic en *Detener*.
. Compruebe que el recurso compartido ya no aparece en la ventana *shares*.




== Crear recursos compartidos de directorios iniciales

Puede usar System Manager para crear un recurso compartido de directorio inicial y gestionar las rutas de búsqueda de directorios iniciales.

.Antes de empezar
CIFS debe estar configurado y iniciado.

.Pasos
. Haga clic en *almacenamiento* > *recursos compartidos*.
. Haga clic en *Crear directorio principal* y, a continuación, proporcione la información de patrón que determina cómo se asigna un usuario a un directorio.
. Haga clic en *Crear*.
. Compruebe que el directorio inicial que ha creado aparece en la ventana *shares*.




== Editar la configuración de recursos compartidos

Puede usar System Manager para modificar la configuración de un recurso compartido, como la configuración del enlace simbólico, los permisos de acceso al recurso compartido de los usuarios o los grupos, y el tipo de acceso a dicho recurso. También puede habilitar o deshabilitar la disponibilidad continua de un recurso compartido mediante Hyper-V, así como habilitar o deshabilitar la enumeración basada en acceso (ABE). A partir de System Manager 9.6, es compatible con la disponibilidad continua de los volúmenes FlexGroup.

.Pasos
. Haga clic en *almacenamiento* > *recursos compartidos*.
. Seleccione el recurso compartido que desea modificar en la lista de recursos compartidos y, a continuación, haga clic en *Editar*.
. En el cuadro de diálogo *Editar configuración de recurso compartido*, modifique la configuración del recurso compartido según sea necesario:
+
.. En la ficha *General*, active la disponibilidad continua de un recurso compartido mediante Hyper-V.
+
La habilitación de la disponibilidad continua permite a SMB 3.0 y los clientes que admiten SMB 3.0 abrir archivos de forma persistente durante operaciones no disruptivas. Los archivos que se abren de forma persistente están protegidos de eventos disruptivos como conmutación por error, devolución y migración de LIF.

.. En la ficha *permisos* , agregue usuarios o grupos y, a continuación, asigne permisos para especificar el tipo de acceso.
.. En la ficha *Opciones*, seleccione las opciones necesarias.


. Haga clic en *Guardar y cerrar*.
. Compruebe los cambios realizados en el recurso compartido seleccionado en la ventana *shares*.




== Cómo habilita ONTAP los directorios iniciales dinámicos

Los directorios iniciales de ONTAP permiten configurar un recurso compartido de SMB que se asigna a directorios diferentes en función del usuario que se conecta a él y a un conjunto de variables. En lugar de crear recursos compartidos independientes para cada usuario, puede configurar un recurso compartido con algunos parámetros del directorio inicial para definir la relación de un usuario entre un punto de entrada (el recurso compartido) y el directorio inicial (un directorio en la SVM).

Un usuario que ha iniciado sesión como usuario invitado no tiene un directorio principal y no puede acceder a los directorios iniciales de otros usuarios. Existen cuatro variables que determinan cómo se asigna un usuario a un directorio:

* *Nombre del recurso compartido*
+
Éste es el nombre del recurso compartido que se crea al que se conecta el usuario. Debe establecer la propiedad del directorio principal para este recurso compartido.

+
El nombre del recurso compartido puede utilizar los siguientes nombres dinámicos:

+
** `%w` (Nombre de usuario de Windows del usuario)
** `%d` (Nombre de dominio de Windows del usuario)
** `%u` (Nombre de usuario UNIX asignado del usuario)


+
Para que el nombre del recurso compartido sea único en todos los directorios iniciales, el nombre del recurso compartido debe contener cualquiera de los dos/`%w` o la `%u` variable. El nombre del recurso compartido puede contener ambos `%d` y la/`%w` variable (por ejemplo, `%d`/`%w`), o el nombre del recurso compartido puede contener una parte estática y una parte variable (por ejemplo, home_/`%w`).

* *Compartir ruta*
+
Esta es la ruta relativa, que define el recurso compartido y, por lo tanto, está asociada con uno de los nombres de recurso compartido, que se anexa a cada ruta de búsqueda para generar toda la ruta de directorio inicial del usuario desde la raíz de la SVM. Puede ser estático (por ejemplo, `home`), dinámico (por ejemplo, `%w`), o una combinación de los dos (por ejemplo, `eng/%w`).

* *Rutas de búsqueda*
+
Este es el conjunto de rutas absolutas desde la raíz de la SVM que especifique que dirige la búsqueda ONTAP de directorios iniciales. Puede especificar una o varias rutas de búsqueda mediante el `vserver cifs home-directory search-path add` comando. Si especifica varias rutas de búsqueda, ONTAP las intenta en el orden especificado hasta que encuentre una ruta válida.

* *Directorio*
+
Éste es el directorio principal del usuario que se crea para el usuario. El nombre del directorio suele ser el nombre del usuario. Debe crear el directorio principal en uno de los directorios definidos por las rutas de búsqueda.



Por ejemplo, considere la siguiente configuración:

* Usuario: John Smith
* Dominio de usuario: acme
* Nombre de usuario: Jsmith
* Nombre de SVM: vs1
* Directorio principal nombre compartido #1: home_ `%w` - vía compartida: `%w`
* Nombre del recurso compartido del directorio inicial #2: `%w` - vía compartida: `%d/%w`
* Ruta de búsqueda #1: `/vol0home/home`
* Ruta de búsqueda #2: `/vol1home/home`
* Ruta de búsqueda #3: `/vol2home/home`
* Directorio inicial: `/vol1home/home/jsmith`


Escenario 1: El usuario se conecta a. `\\vs1\home_jsmith`. Esto coincide con el nombre del primer recurso compartido del directorio principal y genera la ruta de acceso relativa `jsmith`. ONTAP busca ahora un directorio llamado `jsmith` comprobando cada ruta de búsqueda en orden:

* `/vol0home/home/jsmith` no existe; pasar a la ruta de búsqueda #2.
* `/vol1home/home/jsmith` existe; por lo tanto, la ruta de búsqueda #3 no está activada; el usuario está conectado a su directorio principal.


Escenario 2: El usuario se conecta a. `\\vs1\jsmith`. Esto coincide con el segundo nombre del recurso compartido del directorio principal y genera la ruta de acceso relativa `acme/jsmith`. ONTAP busca ahora un directorio llamado `acme/jsmith` comprobando cada ruta de búsqueda en orden:

* `/vol0home/home/acme/jsmith` no existe; pasar a la ruta de búsqueda #2.
* `/vol1home/home/acme/jsmith` no existe; se pasa a la ruta de búsqueda #3.
* `/vol2home/home/acme/jsmith` no existe; el directorio principal no existe; por lo tanto, la conexión falla.




== Ventana Shares

Puede utilizar la ventana Shares para gestionar los recursos compartidos y ver información sobre los recursos compartidos de NetApp.



=== Botones de comando

* *Crear Compartir*
+
Abre el cuadro de diálogo Create Share, que permite crear un recurso compartido.

* *Crear directorio inicial*
+
Abre el cuadro de diálogo Crear recurso compartido de directorio inicial, que permite crear un nuevo recurso compartido de directorio raíz.

* *Edición*
+
Abre el cuadro de diálogo Editar configuración, lo que permite modificar las propiedades de un recurso compartido seleccionado.

* *Detener uso compartido*
+
Detiene que el objeto seleccionado se comparta.

* *Actualizar*
+
Actualiza la información de la ventana.





=== Lista de recursos compartidos

La lista de recursos compartidos muestra el nombre y la ruta de cada recurso compartido.

* *Nombre del recurso compartido*
+
Muestra el nombre del recurso compartido.

* *Ruta*
+
Muestra el nombre completo de la ruta de una carpeta, un qtree o un volumen existentes compartido. Los separadores de ruta pueden ser barras diagonales inversas o barras diagonales inversas, aunque ONTAP muestra todos los separadores de ruta como barras diagonales inversas.

* *Directorio particular*
+
Muestra el nombre del recurso compartido del directorio principal.

* *Comentario*
+
Muestra descripciones adicionales del recurso compartido, si las hay.

* *Compartir* continuamente disponible
+
Muestra si el recurso compartido está habilitado para una disponibilidad continua. A partir de System Manager 9.6, es compatible con la disponibilidad continua de los volúmenes FlexGroup.





=== El área Detalles

El área situada debajo de la lista de recursos compartidos muestra las propiedades del recurso compartido y los derechos de acceso de cada recurso compartido.

* *Propiedades*
+
** Nombre
+
Muestra el nombre del recurso compartido.

** Estado de los bloqueos oportunistas
+
Especifica si el recurso compartido utiliza bloqueos oportunistas.

** Se puede examinar
+
Especifica si los clientes de Windows pueden examinar el recurso compartido.

** Muestra Snapshot
+
Especifica si los clientes pueden ver las copias Snapshot.

** Recursos compartidos disponibles de forma continua
+
Especifica si el recurso compartido está habilitado o deshabilitado para la disponibilidad continua. A partir de System Manager 9.6, es compatible con la disponibilidad continua de los volúmenes FlexGroup.

** Enumeración basada en acceso
+
Especifica si la enumeración basada en acceso (ABE) está habilitada o deshabilitada en el recurso compartido.

** BranchCache
+
Especifica si BranchCache está habilitado o deshabilitado en el recurso compartido.

** Cifrado SMB
+
Especifica si el cifrado de datos mediante SMB 3.0 se encuentra habilitado en el nivel de máquina virtual de almacenamiento (SVM) o en el nivel de recurso compartido. Si el cifrado SMB se habilita en el nivel de SVM, el cifrado SMB se aplica a todos los recursos compartidos y el valor se muestra como Enabled (en el nivel de SVM).

** Versiones anteriores
+
Especifica si las versiones anteriores se pueden ver y restaurar desde el cliente.



* *Control de acceso compartido*
+
Muestra los derechos de acceso de los usuarios de dominio, grupos de dominio, usuarios locales y grupos locales del recurso compartido.



*Información relacionada*

xref:task_setting_up_cifs.adoc[Configuración de CIFS]
