---
permalink: online-help-96-97/task_aborting_vault_relationships.html 
sidebar: sidebar 
keywords: abort, snapshot, copy, transfer, online, help, system, manager 
summary: Puede usar System Manager para cancelar o detener una transferencia de datos actualmente en curso. 
---
= Cancele una transferencia de copias Snapshot con System Manager: ONTAP 9.7 y versiones anteriores
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede usar System Manager Classic de ONTAP (disponible en ONTAP 9.7 y anterior) para cancelar o detener una transferencia de datos que está en curso en este momento.

.Pasos
. Haga clic en *Protección* > *Relaciones de volumen*.
. Seleccione la relación para la que desea detener la transferencia de datos y haga clic en *Operaciones* > *Anular*.
. Seleccione la casilla de verificación *Sí, deseo cancelar la transferencia* para confirmar la operación.
. *Opcional:* Active la casilla de verificación *mantener datos parcialmente transferidos* para conservar los datos que ya se han transferido al volumen de destino.
. Haga clic en *Anular*.


.Resultados
El estado de la transferencia se muestra como "'aborto'" hasta que la operación se haya completado y aparezca como "'ralentí'" una vez finalizada la operación.

*Información relacionada*

xref:reference_protection_window.adoc[Ventana de protección]
