---
permalink: online-help-96-97/task_editing_application.html 
sidebar: sidebar 
keywords: edit, application, online, help, provisioned, snapshot, copy 
summary: Puede editar una aplicación aprovisionada para aumentar el tamaño del almacenamiento o gestionar las copias Snapshot de la aplicación. 
---
= Editar una aplicación con System Manager: ONTAP 9.7 y versiones anteriores
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede usar System Manager Classic de ONTAP (disponible en ONTAP 9.7 y versiones anteriores) para editar una aplicación aprovisionada con el fin de aumentar el tamaño del almacenamiento o gestionar las copias Snapshot de la aplicación.

.Acerca de esta tarea
Como administrador de clúster, después de aprovisionar una aplicación, puede editarla para modificar el tamaño del almacenamiento. También puede crear, restaurar o eliminar copias Snapshot de la aplicación. El procedimiento de ejemplo siguiente describe cómo editar una aplicación *contenedor NAS*.

.Pasos
. Haga clic en *aplicaciones y niveles* > *aplicaciones*
. Haga clic en el nombre de la aplicación contenedor NAS.
+
[NOTE]
====
Si alguien agrega nuevas aplicaciones con la CLI o la API de REST mientras visualiza la lista de aplicaciones, no podrá ver esas nuevas aplicaciones al desplazarse por la lista.

====
+
La ficha *Descripción general* de la ventana Detalles de la aplicación: nas muestra la configuración de la aplicación.

. Haga clic en *Editar*.
+
El Edit NAS Container: nas muestra la configuración de tamaño de almacenamiento actual y la dirección *NFS Access - Grant Access to Host*.

. Modifique el valor *Tamaño total de almacenamiento*.
. En el campo unidades de tamaño, seleccione en el menú desplegable para especificar las unidades de tamaño correcto (bytes, MB, GB o TB).
. En el campo *nivel de servicio ONTAP*, seleccione en el menú desplegable para especificar el valor.
. Haga clic en *Guardar*.
. Vuelva a la ventana *Detalles de la aplicación: nas* y seleccione la ficha **copias Snapshot**.
+
Se muestra una lista de copias Snapshot para esta aplicación aprovisionada. Puede utilizar el campo *Buscar* para buscar copias Snapshot por nombre.

. Gestione las copias Snapshot realizando las siguientes tareas según sea necesario:
+
|===
| Tarea | Acciones 


 a| 
Cree
 a| 
Haga clic en *Crear* para crear una nueva copia Snapshot.



 a| 
Restaurar
 a| 
Haga clic en las casillas de verificación situadas junto a las copias snapshot que desea restaurar y, a continuación, haga clic en *Restaurar*.



 a| 
Eliminar
 a| 
Haga clic en las casillas de verificación situadas junto a las copias snapshot que desea eliminar y, a continuación, haga clic en *Eliminar*.

|===

