---
permalink: online-help-96-97/task_setting_snapshot_copy_reserve.html 
sidebar: sidebar 
keywords: set, up, snapshot, copy, reserve, system, manager, online, help 
summary: 'Puede usar System Manager para reservar espacio (medido como porcentaje) para las copias de Snapshot en un volumen. Al establecer la reserva de copias snapshot, puede asignar suficiente espacio en disco para las copias snapshot de modo que no consuman el espacio del sistema de archivos activo.' 
---
= Defina la reserva de copias de Snapshot con System Manager - ONTAP 9.7 y versiones anteriores
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede usar System Manager classic de ONTAP (disponible en ONTAP 9.7 y versiones anteriores) para reservar espacio (medido como porcentaje) para las copias Snapshot en un volumen. Al establecer la reserva de copias snapshot, puede asignar suficiente espacio en disco para las copias snapshot de modo que no consuman el espacio del sistema de archivos activo.

.Acerca de esta tarea
El espacio predeterminado que se reserva para las copias Snapshot es del 5 % para volúmenes DE SAN y VMware.

.Pasos
. Haga clic en *almacenamiento* > *volúmenes*.
. En el menú desplegable del campo *SVM*, seleccione *todas las SVM*.
. Seleccione el volumen para el que desea configurar la reserva de copia Snapshot.
. Haga clic en *más acciones* > *Administrar instantáneas* > *Configuración*.
. Escriba o seleccione el porcentaje de espacio de volumen que desea reservar para las copias Snapshot y, a continuación, haga clic en *Aceptar*.


*Información relacionada*

xref:reference_volumes_window.adoc[Ventana Volumes]
