---
permalink: online-help-96-97/task_cloning_nvme_namespace.html 
sidebar: sidebar 
keywords: system, manager, clone, nvme, namespace, nqn, online, help 
summary: Es posible usar System Manager para crear rápidamente otro espacio de nombres de la misma configuración, ya que puede elegir clonar un espacio de nombres. Es posible asignar el espacio de nombres recién clonado a otro NQN de host. 
---
= Clonar un espacio de nombres de NVMe con System Manager: ONTAP 9.7 y versiones anteriores
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede usar el clásico de System Manager de ONTAP (disponible en ONTAP 9.7 y versiones anteriores) para crear rápidamente otro espacio de nombres de la misma configuración seleccionando la clonado de un espacio de nombres. Es posible asignar el espacio de nombres recién clonado a otro NQN de host.

.Antes de empezar
Debe tener una licencia de FlexClone para clonar un espacio de nombres.

.Acerca de esta tarea
Es posible clonar un espacio de nombres con la asignación de host seleccionada y asociarlo con otro subsistema.

.Pasos
. Haga clic en *NVMe* > *espacios de nombres NVMe*.
. En la ventana *espacios de nombres NVMe*, seleccione el espacio de nombres que desea clonar.
. Si necesita un nombre específico, puede cambiar el nombre del espacio de nombres clonado, pero no es obligatorio.
+
El cuadro de diálogo proporciona un nombre predeterminado del espacio de nombres que se va a clonar.

. Modifique la asignación del subsistema para el espacio de nombres clonado.
. Haga clic en *Aceptar*.
+
El espacio de nombres asignado en línea se clona dentro de la misma SVM con un nombre diferente. No se clonará la asignación de hosts.


