---
permalink: online-help-96-97/task_assigning_volumes_to_storage_qos.html 
sidebar: sidebar 
keywords: assign, volumes, storage, qos, online, help, flexgroup, online, help, quality, serice 
summary: 'Puede limitar el rendimiento de volúmenes FlexVol y volúmenes FlexGroup asignándolos a grupos de políticas de calidad de servicio (QoS) de almacenamiento. Es posible asignar calidad de servicio de almacenamiento a volúmenes nuevos, o bien se pueden modificar los detalles de la calidad de servicio de almacenamiento de los volúmenes que ya están asignados a un grupo de políticas mediante System Manager.' 
---
= Asigne volúmenes a la calidad de servicio de almacenamiento con System Manager: ONTAP 9.7 y versiones anteriores
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede usar el clásico de System Manager de ONTAP (disponible en ONTAP 9.7 y versiones anteriores) para limitar el rendimiento de los volúmenes de FlexVol y los volúmenes de FlexGroup asignando a los grupos de políticas de calidad de servicio de almacenamiento. Es posible asignar calidad de servicio de almacenamiento a volúmenes nuevos, o bien se pueden modificar los detalles de la calidad de servicio de almacenamiento de los volúmenes que ya están asignados a un grupo de políticas mediante System Manager.

.Acerca de esta tarea
* Es posible asignar calidad de servicio de almacenamiento solo a volúmenes de lectura/escritura (rw) que estén en línea.
* No es posible asignar calidad de servicio de almacenamiento a un volumen si se asignan los siguientes objetos de almacenamiento a un grupo de políticas:
+
** La máquina virtual de almacenamiento principal (SVM) del volumen
** LUN secundarios del volumen
** Archivos secundarios del volumen


* Es posible asignar la calidad de servicio de almacenamiento o modificar los detalles de calidad de servicio para un máximo de 10 volúmenes en simultáneo.


.Pasos
. Haga clic en *almacenamiento* > *volúmenes*.
. En el menú desplegable del campo *SVM*, seleccione *todas las SVM*.
. Seleccione uno o varios volúmenes para los cuales desee asignar calidad de servicio de almacenamiento.
. Haga clic en *más acciones* > *QoS de almacenamiento*.
. En el cuadro de diálogo *Detalles de calidad de servicio*, active la casilla de verificación *gestionar calidad de servicio de almacenamiento* si desea administrar el rendimiento de la carga de trabajo del volumen FlexVol.
+
Si algunos de los volúmenes que seleccionó ya están asignados a un grupo de políticas, los cambios que se realizan pueden afectar al rendimiento de estos volúmenes.

. Cree un nuevo grupo de políticas de calidad de servicio de almacenamiento o seleccione un grupo de políticas existente para controlar el rendimiento de entrada/salida (I/o) del volumen de FlexVol:
+
|===
| Si desea... | Realice lo siguiente... 


 a| 
Crear un nuevo grupo de políticas
 a| 
.. Seleccione *Nuevo grupo de políticas*.
.. Escriba el nombre del grupo de políticas.
.. Especifique el límite mínimo de rendimiento.
+
*** En System Manager 9.5, puede establecer el límite mínimo de rendimiento solo con una personalidad de All Flash optimizada basada en el rendimiento. En System Manager 9.6, también puede establecer el límite mínimo de rendimiento para los sistemas ONTAP Select Premium.
*** No puede establecer el límite mínimo de rendimiento para los volúmenes en un agregado habilitado para FabricPool.
*** Si no especifica el valor de rendimiento mínimo o si el valor de rendimiento mínimo se establece en 0, el sistema mostrará automáticamente «'Ninguno'» como valor.
+
Este valor distingue entre mayúsculas y minúsculas.



.. Especifique el límite máximo de rendimiento para evitar que la carga de trabajo de los objetos del grupo de políticas supere el límite de rendimiento establecido.
+
*** El límite mínimo de rendimiento y el límite máximo de rendimiento deben expresarse en el mismo tipo de unidad.
*** Si no especifica el límite mínimo de rendimiento, puede establecer el límite máximo de rendimiento como IOPS, B/s, KB/s, MB/s, etc.
*** Si no especifica el valor de rendimiento máximo, el sistema mostrará automáticamente "'Unlimited'" como valor.
+
Este valor distingue entre mayúsculas y minúsculas. La unidad que especifique no afecta al rendimiento máximo.







 a| 
Seleccione un grupo de políticas existente
 a| 
.. Seleccione *Grupo de políticas existente* y, a continuación, haga clic en *elegir* para seleccionar un grupo de políticas existente en el cuadro de diálogo Seleccionar grupo de políticas.
.. Especifique el límite mínimo de rendimiento.
+
*** En System Manager 9.5, puede establecer el límite mínimo de rendimiento solo con una personalidad de All Flash optimizada basada en el rendimiento. En System Manager 9.6, también puede establecer el límite mínimo de rendimiento para los sistemas ONTAP Select Premium.
*** No puede establecer el límite mínimo de rendimiento para los volúmenes en un agregado habilitado para FabricPool.
*** Si no especifica el valor de rendimiento mínimo o si el valor de rendimiento mínimo se establece en 0, el sistema mostrará automáticamente «'Ninguno'» como valor.
+
Este valor distingue entre mayúsculas y minúsculas.



.. Especifique el límite máximo de rendimiento para evitar que la carga de trabajo de los objetos del grupo de políticas supere el límite de rendimiento establecido.
+
*** El límite mínimo de rendimiento y el límite máximo de rendimiento deben expresarse en el mismo tipo de unidad.
*** Si no especifica el límite mínimo de rendimiento, puede establecer el límite máximo de rendimiento como IOPS, B/s, KB/s, MB/s, etc.
*** Si no especifica el valor de rendimiento máximo, el sistema mostrará automáticamente "'Unlimited'" como valor.
  +
Este valor distingue entre mayúsculas y minúsculas. La unidad que especifique no afecta al rendimiento máximo.


+
Si el grupo de políticas se ha asignado a más de un objeto, el rendimiento máximo que se configure se compartirá entre todos los objetos.



|===
. *Opcional:* haga clic en el vínculo que especifica el número de volúmenes si desea revisar la lista de volúmenes seleccionados y, a continuación, haga clic en *descartar* si desea eliminar cualquier volumen de la lista.
+
El enlace solo se muestra cuando se seleccionan varios volúmenes.

. Haga clic en *Aceptar*.

