---
permalink: nfs-config-esxi/task_configuring_your_network_for_best_performance.html 
sidebar: sidebar 
keywords: ethernet, network, performance, configuration, value, configure, configure your network for best performance 
summary: Las redes Ethernet varían en gran medida en cuanto al rendimiento. Puede maximizar el rendimiento de la red seleccionando valores de configuración específicos. 
---
= Configure su red para obtener el mejor rendimiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las redes Ethernet varían en gran medida en cuanto al rendimiento. Puede maximizar el rendimiento de la red seleccionando valores de configuración específicos.

.Pasos
. Conecte los puertos de host y de almacenamiento a la misma red.
+
Se recomienda conectarse a los mismos conmutadores.

. Seleccione los puertos de mayor velocidad disponibles.
+
Los puertos de 10 GbE o más rápidos son los mejores. Los puertos de 1 GbE son el mínimo.

. Habilite las tramas gigantes si lo desea y lo admite su red.
+
Las tramas gigantes deben tener una MTU de 9000 para hosts ESXi y sistemas de almacenamiento, y 9216 para la mayoría de switches. Todos los dispositivos de red de la ruta de datos, incluidas las NIC ESXi, las NIC de almacenamiento y los switches, deben admitir tramas gigantes y deben configurarse para sus valores máximos de MTU.

+
Para obtener más información, consulte link:https://docs.netapp.com/us-en/ontap/performance-admin/check-network-settings-data-switches-task.html["Compruebe la configuración de red en los switches de datos"^] y la documentación del proveedor de switches.


