---
permalink: fc-config-esxi/task_creating_svm.html 
sidebar: sidebar 
keywords: storage, virutal, machine, svm, fc, target, host, access, lun, logical, lif, function, user, cluster, create a new svm 
summary: La máquina virtual de almacenamiento proporciona el destino FC a través del cual un host accede a las LUN. 
---
= Cree una SVM nueva
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La máquina virtual de almacenamiento (SVM) proporciona el destino FC a través del cual un host accede a los LUN. Cuando crea la SVM, también crea interfaces lógicas (LIF) que proporcionan rutas a la LUN. Es posible crear una SVM para separar las funciones de administración y datos de un usuario de las de otros usuarios en un clúster.

.Antes de empezar
* Debe configurarse la estructura FC y los puertos físicos deseados deben conectarse a la estructura.


.Pasos
. Vaya a la ventana *SVMs*.
. Haga clic en *Crear*.
. En la ventana *Storage Virtual Machine (SVM) Setup* (Configuración de la máquina virtual de almacenamiento), cree la SVM:
+
.. Especifique un nombre único para la SVM.
+
El nombre debe ser un nombre de dominio completo (FQDN) o seguir otra convención que garantice nombres únicos en un clúster.

.. Seleccione el espacio IP al que pertenecerá la SVM.
+
Si el clúster no utiliza varios espacios IP, se utiliza el espacio IP «predeterminado».

.. Mantenga la selección de tipo de volumen predeterminada.
+
Solo los volúmenes FlexVol son compatibles con protocolos SAN.

.. Seleccione todos los protocolos para los que tenga licencias y para los que pueda usar en la SVM, incluso si no desea configurar todos los protocolos inmediatamente.
+
Al seleccionar NFS y CIFS cuando se crea la SVM, estos dos protocolos pueden compartir las mismas LIF. Al agregar más adelante estos protocolos no los permite compartir LIF.

+
Si CIFS es uno de los protocolos seleccionados, el estilo de seguridad se establece en NTFS. De lo contrario, el estilo de seguridad se establece en UNIX.

.. Mantenga la configuración de idioma predeterminada C.UTF-8.
.. Seleccione el agregado raíz deseado para contener el volumen raíz de SVM.
+
El agregado para el volumen de datos se selecciona por separado en el paso posterior.

.. Haga clic en *Enviar y continuar*.


+
La SVM se ha creado, pero aún no se han configurado los protocolos.

. Si aparece la página *Configurar protocolo CIFS/NFS* porque ha activado CIFS o NFS, haga clic en *Omitir* y, a continuación, configure CIFS o NFS más adelante.
. Si aparece la página *Configurar protocolo iSCSI* porque ha habilitado iSCSI, haga clic en *Omitir* y, a continuación, configure iSCSI más tarde.
. Configure el servicio FC y las LIF desde la página *Configurar protocolo FC/FCoE*:
+
.. Active la casilla de verificación *Configurar LIF de datos para FC*.
.. Introduzca `2` En el campo *LIF por nodo*.
+
Por cada nodo se necesitan dos LIF para garantizar la disponibilidad y la movilidad de datos.

.. Omitir el área opcional *aprovisionar un LUN para el almacenamiento FCP* porque el LUN es aprovisionado por Virtual Storage Console para VMware vSphere en un paso posterior.
.. Haga clic en *Enviar y continuar*.


. Cuando aparezca *Administración de SVM*, configure o aplace la configuración de un administrador independiente para esta SVM:
+
** Haga clic en *Omitir* y configure un administrador más tarde si lo desea.
** Introduzca la información solicitada y, a continuación, haga clic en *Enviar y continuar*.


. Revise la página *Resumen*, registre la información de LIF y, a continuación, haga clic en *Aceptar*.

