---
permalink: fc-config-rhel/index.html 
sidebar: sidebar 
keywords: fc, service, storage, virtual, machine, svm, provision, lun, fc, host, bus, adapter, hba, linux, server, configuration, red hat enterprise linux 
summary: Puede configurar rápidamente el servicio FC en una máquina virtual de almacenamiento, aprovisionar un LUN y hacer que el LUN esté disponible mediante un adaptador de bus de host FC en un servidor Red Hat Enterprise Linux. 
---
= Información general sobre la configuración de FC para Red Hat Enterprise Linux
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible configurar rápidamente el servicio FC en una máquina virtual de almacenamiento (SVM), aprovisionar un LUN y hacer que el LUN esté disponible mediante un adaptador de bus de host (HBA) de FC en un servidor Red Hat Enterprise Linux mediante la interfaz clásica de System Manager de ONTAP (ONTAP 9.7 y versiones anteriores).

Utilice este procedimiento para configurar el servicio FC en una SVM si:

* El host ejecuta una versión admitida de Red Hat Enterprise Linux 6.4 o posterior.
* Utiliza switches y HBA de FC tradicionales.
+

NOTE: Fibre Channel sobre Ethernet (FCoE) no se incluye en este procedimiento.

* Tiene al menos dos puertos de destino FC disponibles en cada nodo del clúster.
Pueden configurarse los puertos FC y UTA2 integrados (también llamados «'CNA'»), así como algunos adaptadores. La configuración de esos puertos se realiza en la interfaz de línea de comandos (CLI) de ONTAP y no se trata en este procedimiento.
* No está configurando el arranque SAN FC.


Si estas suposiciones no son correctas para su situación, debería consultar los recursos siguientes:

* https://docs.netapp.com/us-en/ontap/san-admin/index.html["Administración de SAN"^]
* https://docs.netapp.com/us-en/ontap/san-config/index.html["CONFIGURACIÓN DE SAN"^]
* https://docs.netapp.com/us-en/ontap-sanhost/hu_luhu_71.html["Instalación de Linux Unified Host Utilities 7.1"^]




== Otras maneras de hacerlo en ONTAP

|===


| Para ejecutar estas tareas con... | Consulte... 


| System Manager rediseñado (disponible con ONTAP 9.7 y versiones posteriores) | link:https://docs.netapp.com/us-en/ontap/task_san_provision_linux.html["Aprovisionar almacenamiento SAN para servidores Linux"^] 


| La interfaz de línea de comandos (CLI) de ONTAP | link:https://docs.netapp.com/us-en/ontap/san-admin/lun-setup-workflow-concept.html["Flujo de trabajo de configuración de LUN con la CLI"^] 
|===