---
permalink: fc-config-rhel/task_verifying_that_host_can_write_to_read_fom_lun.html 
sidebar: sidebar 
keywords: multipath, device, verify, host, write, data, verify that the host can write to and read from a multipath device 
summary: Antes de utilizar un dispositivo multivía, debe verificar que el host puede escribir datos en el dispositivo multivía y leerlos nuevamente. 
---
= Verifique que el host pueda escribir en un dispositivo multivía y leerlo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de utilizar un dispositivo multivía, debe verificar que el host puede escribir datos en el dispositivo multivía y leerlos nuevamente.

.Antes de empezar
DM-Multipath debe configurarse en el host Linux para los nodos del clúster de almacenamiento a los que acceda.

.Acerca de esta tarea
Si el nodo de clúster de almacenamiento al que corresponde el dispositivo multivía puede realizar una conmutación por error a su nodo compañero, debe verificar la lectura de los datos mientras se da un error en el nodo. Esta verificación podría no ser posible si el clúster de almacenamiento se está utilizando en producción.

.Pasos
. Ejecute algunas operaciones de I/o en el dispositivo multivía especificado:
+
`dd if=/dev/zero of=<multipath_device_name\>`

. Verifique que la I/o se esté ejecutando en el dispositivo multivía, especificando la cantidad de segundos que se deben actualizar las estadísticas (por ejemplo, cada dos segundos, como se muestra):
+
`iostat 2`

+
Cuando la E/S se ejecuta en el dispositivo multivía, puede ver los distintos contadores de I/o cambian de forma dinámica la salida, lo que indica que la I/o se está ejecutando correctamente en el dispositivo multivía.

+
[listing]
----
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
            0.00    0.00    0.01    0.00    0.00   99.98

Device:            tps   Blk_read/s   Blk_wrtn/s   Blk_read   Blk_wrtn
sda               0.18         1.34         2.29     832606    1428026
dm-0              0.37         1.29         2.29     801530    1427984
dm-1              0.00         0.00         0.00       2576          0
dm-2              0.00         0.00         0.00       1770         24
sdd               0.17         1.18        17.87     734688   11128584
sde               0.17         1.18        18.01     734560   11219016
sdf               0.00         0.00         0.00       1344          0
sdg               0.00         0.00         0.00       1344          0
dm-3              0.68         4.71        71.96    2932496   44816008
sdh               0.17         1.18        18.22     734360   11343920
sdi               0.17         1.18        17.86     734272   11124488
sdj               0.00         0.00         0.00       1344          0
sdk               0.00         0.00         0.00       1344          0
.............
----
. Si es posible, ejecute el `takeover` comando en el nodo del clúster de almacenamiento:
+
`storage failover takeover -ofnode <node_name\>`

. Compruebe que la actividad de I/o sigue en ejecución en el dispositivo multivía; para ello, vuelva a ejecutar el``iostat`` comando.
. Ejecute el `giveback` comando en el nodo del clúster de almacenamiento:
+
`storage failover giveback -ofnode <node_name\>`

. Comprobar `iostat` Salida para verificar que la I/o sigue en ejecución.




== Qué hacer a continuación

Si alguna de las pruebas presenta errores, compruebe que el servicio FC esté en ejecución y vuelva a comprobar la configuración de DM-Multipath y las rutas FC al dispositivo multivía.
