---
permalink: fc-config-rhel/task_discovering_new_scsi_devices_dm_multipath_devices.html 
sidebar: sidebar 
keywords: lun, storage, cluster, linux, host, scsi, device, i/o, dm-multipath, aggregate, device, multipath, automatic, rescan, discover new scsi device luns and multipath device 
summary: 'Las LUN del clúster de almacenamiento aparecen en el host Linux como dispositivos SCSI, que son rutas de I/o que los agregados DM-Multipath en un nuevo dispositivo, denominado dispositivo multivía. El host no detecta automáticamente nuevos dispositivos SCSI (LUN) que agrega al sistema. Debe volver a detectarlos manualmente para detectarlos.' 
---
= Detectar nuevos dispositivos SCSI (LUN) y dispositivos multivía
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las LUN del clúster de almacenamiento aparecen en el host Linux como dispositivos SCSI, que son rutas de I/o que los agregados DM-Multipath en un nuevo dispositivo, denominado dispositivo multivía. El host no detecta automáticamente nuevos dispositivos SCSI (LUN) que agrega al sistema. Debe volver a detectarlos manualmente para detectarlos.

.Antes de empezar
Debe tener una copia del `rescan` script, que se encuentra en la `sg3_utils` Paquete que forma parte de su distribución de Linux OS.

.Pasos
. Detecte nuevos dispositivos SCSI (LUN) y cree los dispositivos multivía correspondientes para las LUN: `/usr/bin/rescan-scsi-bus.sh`
. Verificar la configuración de DM-Multipath:
+
`multipath -ll`

+
Esto muestra el siguiente tipo de resultado, con una lista de la configuración recomendada para cada LUN de NetApp:

+
[listing]
----
3600a0980324666546e2b443251655177 dm-2 NETAPP,LUN C-Mode
size=10G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='round-robin 0' prio=50 status=active
| |- 0:0:1:0 sdb 8:16  active ready  running
| |- 0:0:0:0 sda 8:0   active ready  running
| |- 1:0:0:0 sde 8:64  active ready  running
| `- 1:0:1:0 sdf 8:80  active ready  running
`-+- policy='round-robin 0' prio=10 status=enabled
  |- 0:0:3:0 sdd 8:48  active ready  running
  |- 1:0:3:0 sdh 8:112 active ready  running
  |- 0:0:2:0 sdc 8:32  active ready  running
  `- 1:0:2:0 sdg 8:96  active ready  running
----

