---
permalink: iscsi-config-rhel/index.html 
sidebar: sidebar 
keywords: iscsi, service, storage, virtual, machine, svm, lun, initiator, red, hat, enterprise, linux, server, configuration, san, provision, provisioning 
summary: Estos procedimientos describen cómo configurar rápidamente el servicio iSCSI en una máquina virtual de almacenamiento, aprovisionar un LUN y hacer que el LUN esté disponible mediante un iniciador iSCSI en un servidor Red Hat Enterprise Linux. 
---
= Información general sobre la configuración de iSCSI para Red Hat Enterprise Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Con la interfaz clásica de System Manager de ONTAP (ONTAP 9.7 y versiones anteriores), puede configurar rápidamente el servicio iSCSI en una máquina virtual de almacenamiento (SVM), aprovisionar un LUN y hacer que el LUN esté disponible en un servidor Red Hat Enterprise Linux.

Estos procedimientos se basan en las siguientes suposiciones:

* Utiliza el iniciador de software iSCSI en un host Red Hat Enterprise Linux que ejecuta una versión compatible de RHEL Series 6.4 o posterior.
* La red utiliza direcciones IPv4.
* Desea asignar direcciones a interfaces lógicas mediante cualquiera de los siguientes métodos:
+
** Automáticamente, desde una subred que defina
** Manualmente, usando una dirección seleccionada de una subred existente
** Manualmente, usando una dirección que se añadirá a una subred existente


* No está configurando el arranque SAN iSCSI.


Para obtener más información acerca de cómo configurar el host específico con ONTAP, consulte https://docs.netapp.com/us-en/ontap-sanhost/index.html["Configuración de host SAN ONTAP"].

Si quiere más información sobre la administración DE SAN, consulte https://docs.netapp.com/us-en/ontap/san-admin/index.html["Descripción general de la administración DE SAN de ONTAP 9"]



== Otras maneras de hacerlo en ONTAP

|===


| Para completar esta tarea mediante... | Consulte... 


| System Manager de nuevo diseño (disponible con la versión 9.7 y posterior) | https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["Aprovisionar el almacenamiento SAN"^] 


| La interfaz de línea de comandos (CLI) de ONTAP | https://docs.netapp.com/us-en/ontap/san-admin/lun-setup-workflow-concept.html["Flujo de trabajo de configuración de LUN con la CLI"^] 
|===