---
permalink: iscsi-config-windows/task_verifying_that_iscsi_fc_configuration_is_supported.html 
sidebar: sidebar 
keywords: reliable, operation, verify, iscsi, configuration, support, verify that the iscsi configuration is supported 
summary: Para lograr un funcionamiento fiable, es necesario verificar que toda la configuración de iSCSI sea compatible. 
---
= Compruebe que la configuración de iSCSI es compatible
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para lograr un funcionamiento fiable, es necesario verificar que toda la configuración de iSCSI sea compatible.

.Pasos
. Vaya a la matriz de interoperabilidad para verificar que cuenta con una combinación compatible de los siguientes componentes:
+
** Software ONTAP
** Arquitectura de CPU de ordenador host (para servidores de bastidor estándar)
** Modelo blade de procesador específico (para servidores blade)
** Protocolo de almacenamiento (iSCSI)
** Versión del sistema operativo Windows
** Utilidades unificadas de host de Windows


. Haga clic en el nombre de la configuración seleccionada.
+
Los detalles de esa configuración se muestran en la ventana Detalles de configuración.

. Revise la información en las siguientes pestañas:
+
** Notas
+
Enumera las alertas e información importantes que son específicas de su configuración.

+
Revise las alertas para identificar las correcciones urgentes que se requieren para el sistema operativo.

** Políticas y directrices
+
Proporciona directrices generales para todas las configuraciones DE SAN.




