---
permalink: smb-config/index.html 
sidebar: sidebar 
keywords: content, describe, smb, cifs, access, volume, exist, storage, virtual, machine, svm, system manager classic 
summary: 'Con la interfaz clásica de System Manager de ONTAP (ONTAP 9.7 y versiones anteriores), es posible configurar rápidamente el acceso de SMB/CIFS a un volumen nuevo en una máquina virtual de almacenamiento nueva o existente (SVM)' 
---
= Información general de la configuración de SMB/CIFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Con la interfaz clásica de System Manager de ONTAP (ONTAP 9.7 y versiones anteriores), es posible configurar rápidamente el acceso de SMB/CIFS a un volumen nuevo en una máquina virtual de almacenamiento nueva o existente.

Utilice este procedimiento si desea configurar el acceso a un volumen de la siguiente manera:

* Quiere utilizar las prácticas recomendadas, no explorar todas las opciones disponibles.
* La red de datos utiliza el espacio IP predeterminado, el dominio de retransmisión predeterminado y el grupo de conmutación por error predeterminado.
+
Si la red de datos es fija, el uso de estos objetos predeterminados garantiza que las LIF se conmutarán al nodo de respaldo en caso de que falle el enlace. Si no está utilizando los objetos predeterminados, debe hacer referencia a https://docs.netapp.com/us-en/ontap/networking/index.html["Documentación de gestión de redes"^] Para obtener información sobre cómo configurar la conmutación al nodo de respaldo de la ruta de LIF.

* Se utilizarán permisos de archivo NTFS para proteger el nuevo volumen.


Si desea obtener detalles acerca del rango de funcionalidades del protocolo SMB de ONTAP, consulte la link:https://docs.netapp.com/us-en/ontap/smb-admin/index.html["Información general sobre la referencia de SMB"^].



== Otras maneras de hacerlo en ONTAP

|===


| Para ejecutar estas tareas con... | Consulte... 


| System Manager rediseñado (disponible con ONTAP 9.7 y versiones posteriores) | link:https://docs.netapp.com/us-en/ontap/task_nas_provision_windows_smb.html["Aprovisionar almacenamiento NAS para servidores de Windows mediante SMB"^] 


| La interfaz de línea de comandos de ONTAP | link:https://docs.netapp.com/us-en/ontap/smb-config/index.html["Información general de configuración de SMB con la CLI"^] 
|===