---
permalink: expansion/concept_configuring_node_management_lifs.html 
sidebar: sidebar 
keywords: controller, module, physical, install, power, configure, node-mangement, lif, configure node-management lifs 
summary: Después de instalar físicamente los módulos de la controladora, puede encender cada uno y configurar su LIF de gestión de nodos. 
---
= Configure los LIF de gestión de nodos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de instalar físicamente los módulos de la controladora, puede encender cada uno y configurar su LIF de gestión de nodos.

.Acerca de esta tarea
Debe realizar este procedimiento en los dos nodos.

.Pasos
. Acceda al módulo de la controladora a través de la consola de serie.
. Encienda el módulo de la controladora y espere mientras arranca el nodo y el Asistente de configuración de clúster se inicia automáticamente en la consola.
+
[listing]
----
Welcome to the cluster setup wizard.

You can enter the following commands at any time:
  "help" or "?" - if you want to have a question clarified,
  "back" - if you want to change previously answered questions, and
  "exit" or "quit" - if you want to quit the cluster setup wizard.
   Any changes you made before quitting will be saved.

You can return to cluster setup at any time by typing "cluster setup".
To accept a default or omit a question, do not enter a value.
----
. Siga las instrucciones del asistente de configuración de clúster basado en web para configurar una LIF de gestión de nodos con la información de red recopilada anteriormente.
. Tipo `exit` Una vez finalizada la configuración de LIF de gestión del nodo, para salir del asistente de configuración y completar las tareas de administración.
+
[listing]
----
Use your web browser to complete cluster setup by accessing
https://10.63.11.29

Otherwise, press Enter to complete cluster setup using the command line interface:
exit
----
. Inicie sesión en el nodo como el `admin` usuario, que no requiere contraseña.
+
[listing]
----
Tue Mar 4 23:13:33 UTC 2015
login: admin
******************************************************
* This is a serial console session. Output from this *
* session is mirrored on the SP console session.     *
----
. Repita todo el procedimiento para el segundo módulo de controlador recién instalado.

