---
permalink: expansion/task_adding_nodes_to_cluster_using_system_manager.html 
sidebar: sidebar 
keywords: system, manager, increase, size, capabilities, capability, storage, node, automatic, ontap, add nodes to a cluster using system manager 
summary: Puede usar System Manager para aumentar el tamaño y las funcionalidades del sistema de almacenamiento mediante la adición de nodos a un clúster existente. Esta función se habilita automáticamente en System Manager cuando la versión del clúster efectivo es ONTAP 9.2. 
---
= Añada nodos a un clúster mediante System Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede usar System Manager para aumentar el tamaño y las funcionalidades del sistema de almacenamiento mediante la adición de nodos a un clúster existente. Esta función se habilita automáticamente en System Manager cuando la versión del clúster efectivo es ONTAP 9.2.

.Antes de empezar
* Deben cablearse nuevos nodos compatibles con el clúster.
+
Sólo los puertos que están en el dominio de difusión predeterminado se mostrarán en la ventana Red.

* Todos los nodos del clúster deben estar en funcionamiento.
* Todos los nodos deben tener la misma versión.


.Paso
. Añada los nuevos nodos compatibles al clúster:
+
[cols="1,3"]
|===


| Si está... | Realice lo siguiente... 


 a| 
No se ha iniciado sesión en System Manager
 a| 
.. Inicie sesión en System Manager.
+
[NOTE]
====
System Manager detecta automáticamente los nodos compatibles nuevos al iniciar sesión. System Manager le solicita añadir los nuevos nodos compatibles al clúster.

====
.. Haga clic en *Agregar nodos al clúster*.
.. Modifique el nombre de los nodos.
.. Especifique las licencias de nodo.
.. Haga clic en *Enviar y continuar*.




 a| 
Inició sesión en System Manager
 a| 
.. Según la versión de System Manager que esté ejecutando, realice uno de los pasos siguientes:
+
*** ONTAP 9.4 o anterior: Haga clic en *Configuración* > *expansión de clúster*.
*** A partir de ONTAP 9,5: Haga clic en *Configuración* > *Clúster* > *Expansión*
System Manager buscará nodos añadidos recientemente. Si se muestra alguna advertencia, debe solucionarla antes de continuar. Si se detectan nuevos nodos compatibles, continúe con el siguiente paso.


.. Modifique el nombre de los nodos.
.. Especifique las licencias de nodo.
.. Haga clic en *Enviar y continuar*.


|===

