---
permalink: expansion/task_backing_up_cluster_configuration.html 
sidebar: sidebar 
keywords: expand, cluster, advance, privilege, backup, file, configuration, information, back up the cluster configuration 
summary: Antes de expandir un clúster, debe utilizar un privilegio avanzado para crear un archivo de backup para guardar la información de configuración del clúster y, opcionalmente, guardar las configuraciones de los nodos. 
---
= Realice un backup de la configuración del clúster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de expandir un clúster, debe utilizar un privilegio avanzado para crear un archivo de backup para guardar la información de configuración del clúster y, opcionalmente, guardar las configuraciones de los nodos.

.Pasos
. Configure el nivel de privilegio en Advanced mediante el `set -privilege advanced` comando.
. Cree un archivo de backup de la configuración del clúster mediante el `system configuration backup create` con el `-backup-type cluster` parámetro.
+
[listing]
----
cluster1::*> system configuration backup create -node cluster1-1 -backup-name clusterbeforeexpansion.7z -backup-type cluster
[Job 5573] Job is queued: Cluster Backup OnDemand Job.
----
. Cree un archivo de copia de seguridad de la configuración de cada nodo mediante el `system configuration backup create` con el `-backup-type node` parámetro para cada nodo.
. Devuelva el nivel de privilegio a admin mediante el `set -privilege admin` comando.

