---
permalink: expansion/task_adding_or_replacing_switches.html 
sidebar: sidebar 
keywords: expand, cluster, ensure, configuration, switch, exist, port, add, replace, add or replace switches 
summary: Antes de expandir el clúster, debe asegurarse de que los switches de clúster admitan la configuración expandida. Si el clúster no tiene switch, debe añadir switches. 
---
= Agregar o sustituir interruptores
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de expandir el clúster, debe asegurarse de que los switches de clúster admitan la configuración expandida. Si el clúster no tiene switch, debe añadir switches. Si los switches existentes no tienen suficientes puertos disponibles para admitir la nueva configuración, debe reemplazar los switches.



== Procedimiento

* Si el clúster es actualmente un clúster sin switches de dos nodos, migre el clúster a un clúster con switches de dos nodos mediante el tipo de switch que prefiera.
+
https://library.netapp.com/ecm/ecm_download_file/ECMP1140536["Migración a un clúster con switches de dos nodos con switches de clúster de Cisco"]

+
https://library.netapp.com/ecm/ecm_download_file/ECMP1140535["Migración a un clúster con switches de dos nodos con switches de clúster CN1610 de NetApp"]

* Si los switches existentes no tienen suficientes puertos disponibles para admitir la configuración futura, sustituya los switches por el procedimiento de sustitución adecuado.
+
https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62371["Documentación de NetApp: Switches de clúster, gestión y almacenamiento"]


