---
permalink: volume-restore-snapvault/task_identifying_snapvault_backup_destination_volume.html 
sidebar: sidebar 
keywords: identify, snapvault, backup, destination, volume, restore, data, source, corrupt, identify the snapvault backup destination volume 
summary: Debe identificar el volumen de destino de backup de SnapVault desde el cual desea restaurar datos cuando los datos del volumen de origen se pierden o se dañan. 
---
= Identificar el volumen de destino del backup SnapVault
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe identificar el volumen de destino de backup de SnapVault desde el cual desea restaurar datos cuando los datos del volumen de origen se pierden o se dañan.

.Acerca de esta tarea
Debe realizar esta tarea desde el clúster *fuente*.

.Pasos
. Introduzca la URL `+https://IP-address-of-cluster-management-LIF+` En un explorador web e inicie sesión en System Manager con la credencial de administrador de clúster.
. Vaya a la ventana *Volumes*.
. Identifique el volumen de destino en la relación SnapVault y el nombre de la SVM que contiene el volumen:
+
** ONTAP 9.3 o posterior: Haga doble clic en el volumen para ver los detalles y, a continuación, haga clic en *PROTECCIÓN*.
** ONTAP 9.2 o anterior: Haga clic en la ficha *Protección de datos* en la parte inferior de la ventana Volumes.



